repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: go fmt ./...
        language: system
        types: [go]
        pass_filenames: false
      - id: vet
        name: vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false
