version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somepassword
      POSTGRES_DB: postgres
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
