// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMyuuid holds the string denoting the myuuid field in the database.
	FieldMyuuid = "myuuid"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeTodos holds the string denoting the todos edge name in mutations.
	EdgeTodos = "todos"
	// Table holds the table name of the user in the database.
	Table = "users"
	// TodosTable is the table that holds the todos relation/edge. The primary key declared below.
	TodosTable = "user_todos"
	// TodosInverseTable is the table name for the Todo entity.
	// It exists in this package in order to avoid circular dependency with the "todo" package.
	TodosInverseTable = "todos"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldMyuuid,
	FieldName,
}

var (
	// TodosPrimaryKey and TodosColumn2 are the table columns denoting the
	// primary key for the todos relation (M2M).
	TodosPrimaryKey = []string{"user_id", "todo_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
